language: python
python:
- '2.7'
script: wok -v
env:
  global:
    secure: MSwgU/Tw12zZ8Wz8++sUdn9KcIST+QM+0LWmILiG6Fr1qIVJpIWoUfEg6R3Y3kiYhx1Xu4Fo3BgufmFDhyIVyyRqX14sB9gNPJlmhwMa6rhWTM2GbAKZLFY/+O8NbKuB+FtHa8HltObAejTBudjhju335YHYV+1bYF0JutWw4bA=
after_success:
- openssl aes-256-cbc -k "$keypass" -in shh.enc -out idfile -d
- chmod 600 idfile
- rsync -rlpc -e 'ssh -o StrictHostKeyChecking=no -p 31422 -i idfile' --delete-after output/ web@droplet.odysimus.com:/var/www/html
