language: python
python:
- '2.7'
script: wok -v
sudo: false
#env:
#  global:
    #secure: MSwgU/Tw12zZ8Wz8++sUdn9KcIST+QM+0LWmILiG6Fr1qIVJpIWoUfEg6R3Y3kiYhx1Xu4Fo3BgufmFDhyIVyyRqX14sB9gNPJlmhwMa6rhWTM2GbAKZLFY/+O8NbKuB+FtHa8HltObAejTBudjhju335YHYV+1bYF0JutWw4bA=
after_success:
- openssl aes-256-cbc -K $encrypted_377b3159818f_key -iv $encrypted_377b3159818f_iv -in privatetkey -out trav -d
- chmod 600 trav
- rsync -rlc -e 'ssh -o StrictHostKeyChecking=no -p 31422 -i trav' --delete-after  output/ web@droplet.odysimus.com:/var/www/html
